"""add unique constraint on corporate_actions

Revision ID: 1bfe8e008c85
Revises: 3ef1fd8d7d2b
Create Date: 2026-08-18 20:38:44.425553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfe8e008c85'
down_revision: Union[str, None] = '3ef1fd8d7d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_corporate_actions_instrument_id', 'corporate_actions', ['instrument_id', 'ex_date', 'action_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_corporate_actions_instrument_id', 'corporate_actions', type_='unique')
    # ### end Alembic commands ###
