"""create core schema

Revision ID: 3ef1fd8d7d2b
Revises: 
Create Date: 2026-08-18 20:02:24.857743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ef1fd8d7d2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('listed_date', sa.Date(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments')),
    sa.UniqueConstraint('symbol', 'exchange', name='uq_instruments_symbol_exchange')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs'))
    )
    op.create_index('ix_job_runs_job_name_run_date', 'job_runs', ['job_name', sa.literal_column('run_date DESC')], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('ratio_from', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ratio_to', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('applied', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_corporate_actions_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corporate_actions'))
    )
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_daily_prices_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_prices')),
    sa.UniqueConstraint('instrument_id', 'trade_date', name='uq_daily_prices_instrument_id')
    )
    op.create_index('ix_daily_prices_instrument_trade_date', 'daily_prices', ['instrument_id', sa.literal_column('trade_date DESC')], unique=False)
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('pe', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pb', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('roce', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_fundamentals_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundamentals')),
    sa.UniqueConstraint('instrument_id', 'as_of_date', name='uq_fundamentals_instrument_id')
    )
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('sma_20', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sma_50', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sma_100', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sma_200', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ema_20', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ema_50', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rsi_14', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('macd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('macd_histogram', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('atr_14', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume_sma_20', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('high_52w', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low_52w', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_indicators_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicators')),
    sa.UniqueConstraint('instrument_id', 'trade_date', name='uq_indicators_instrument_id')
    )
    op.create_index('ix_indicators_instrument_trade_date', 'indicators', ['instrument_id', sa.literal_column('trade_date DESC')], unique=False)
    op.create_table('screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_screens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screens'))
    )
    op.create_index('ix_screens_user_id', 'screens', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watchlists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlists'))
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seen', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_alerts_instrument_id_instruments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], name=op.f('fk_alerts_screen_id_screens'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('screen_id', 'instrument_id', 'trade_date', name='uq_alerts_screen_id')
    )
    op.create_index('ix_alerts_screen_seen_triggered', 'alerts', ['screen_id', 'seen', sa.literal_column('triggered_at DESC')], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_watchlist_items_instrument_id_instruments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name=op.f('fk_watchlist_items_watchlist_id_watchlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_items')),
    sa.UniqueConstraint('watchlist_id', 'instrument_id', name='uq_watchlist_items_watchlist_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    op.drop_index('ix_alerts_screen_seen_triggered', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('watchlists')
    op.drop_index('ix_screens_user_id', table_name='screens')
    op.drop_table('screens')
    op.drop_index('ix_indicators_instrument_trade_date', table_name='indicators')
    op.drop_table('indicators')
    op.drop_table('fundamentals')
    op.drop_index('ix_daily_prices_instrument_trade_date', table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_table('corporate_actions')
    op.drop_table('users')
    op.drop_index('ix_job_runs_job_name_run_date', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_table('instruments')
    # ### end Alembic commands ###
