"""add bse_scrip_code to instruments

Revision ID: 5ddc59844735
Revises: b0f2ac2fff48
Create Date: 2026-08-25 09:09:27.690941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ddc59844735'
down_revision: Union[str, None] = 'b0f2ac2fff48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('bse_scrip_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'bse_scrip_code')
    # ### end Alembic commands ###
