"""add login_attempts table

Revision ID: b0f2ac2fff48
Revises: 1bfe8e008c85
Create Date: 2026-08-20 22:05:11.015746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f2ac2fff48'
down_revision: Union[str, None] = '1bfe8e008c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=320), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index('ix_login_attempts_key_attempted_at', 'login_attempts', ['key', 'attempted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_attempts_key_attempted_at', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
