"""add portfolio_reports and portfolio_report_items tables

Revision ID: c89e7c387ec3
Revises: 5ddc59844735
Create Date: 2026-08-29 18:30:21.338751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89e7c387ec3'
down_revision: Union[str, None] = '5ddc59844735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ticker_count', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolio_reports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_reports'))
    )
    op.create_index('ix_portfolio_reports_user_id', 'portfolio_reports', ['user_id'], unique=False)
    op.create_table('portfolio_report_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('grp', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('pdf_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('zone', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_portfolio_report_items_instrument_id_instruments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['portfolio_reports.id'], name=op.f('fk_portfolio_report_items_report_id_portfolio_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_report_items')),
    sa.UniqueConstraint('report_id', 'ticker', name='uq_portfolio_report_items_report_ticker')
    )
    op.create_index('ix_portfolio_report_items_instrument_id', 'portfolio_report_items', ['instrument_id'], unique=False)
    op.create_index('ix_portfolio_report_items_report_id', 'portfolio_report_items', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portfolio_report_items_report_id', table_name='portfolio_report_items')
    op.drop_index('ix_portfolio_report_items_instrument_id', table_name='portfolio_report_items')
    op.drop_table('portfolio_report_items')
    op.drop_index('ix_portfolio_reports_user_id', table_name='portfolio_reports')
    op.drop_table('portfolio_reports')
    # ### end Alembic commands ###
